DISCORD_BUTTON_POS_X = 95
DISCORD_BUTTON_POS_Y = 945
DISCORD_BUTTON_COLOR_ACTIVATED = '#00AA55'
DISCORD_BUTTON_COLOR_DEACTIVATED = '#333333'
OBSWS_PORT = '4444'
OBSWS_PASSWORD = ''
OBSWS_BLANK_SCENE_NAME = 'blank'
